import turtle
t=turtle.Turtle()
t.speed(10)
def sun():
    t.penup()
    t.goto(200,200)
    t.pendown()
    t.color("yellow")
    t.begin_fill()
    t.circle(50)
    t.end_fill()
    t.color("orange")
    def sun_line(x,y,way):
        t.pensize(3)
        t.penup()
        t.goto(x,y)
        t.pendown()
        t.right(way)
        t.forward(20)
    sun_line(200,200,90)
    sun_line(200,300,180)
    sun_line(250,250,90)
    sun_line(150,250,180)
def mountain(x,y):
    t.color("gray")
    t.begin_fill()
    t.penup()
    t.goto(x,y)
    t.pendown()
    t.forward(200)
    for i in range(2):
        t.right(120)
        t.forward(200)
    t.end_fill()
def rever(x,y):
    t.color("blue")
    t.begin_fill()
    t.penup()
    t.goto(x,y)
    t.pendown()
    for i in range(2):
        t.right(60)
        t.forward(50)
        t.right(120)
        t.forward(250)
    t.end_fill()
def house(x,y):
    t.color("orange")
    t.begin_fill()
    t.penup()
    t.goto(x,y)
    t.pendown()
    t.right(60)
    for i in range(4):
        t.forward(150)
        t.right(90)
    t.end_fill()
    t.color("red")
    t.begin_fill()
    for i in range(3):
        t.forward(150)
        t.left(120)
    t.end_fill()
    t.color("white")
    t.begin_fill()
    t.penup()
    t.goto(x+55,y-100)
    t.pendown()
    for i in range(2):
        t.forward(40)
        t.right(90)
        t.forward(50)
        t.right(90)
    t.end_fill()
def tree(x,y):
    for i in range(3):
        t.begin_fill()
        t.color("brown")
        t.penup()
        t.goto(x,y)
        t.pendown()
        for j in range(2):
            t.forward(10)
            t.right(90)
            t.forward(20)
            t.right(90)
        t.end_fill()
        t.color("green")
        t.begin_fill()
        t.forward(5)
        t.circle(20)
        t.end_fill()
        x=x-65
        y=y-42
def cloud(x,y):
    t.color("blue")
    t.pensize(3)
    t.penup()
    t.goto(-150,200)
    t.pendown()
    for i in range(3):
        t.begin_fill()
        t.circle(25)
        x=x+45
        t.penup()
        t.goto(x,y)
        t.pendown()
        t.end_fill()
    for i in range(2):
        t.begin_fill()
        t.penup()
        t.goto(x-70,y+25)
        t.pendown()
        t.circle(20)
        t.end_fill()
        x=x-40
    t.begin_fill()
    t.penup()
    t.goto(x-10,y+50)
    t.pendown()
    t.circle(15)
    t.end_fill()
sun()
mountain(300,-100)
mountain(300,73)
rever(55,-100)
house(-300,-100)
tree(300,-170)
cloud(-150,200)
turtle.done()